config/routes.rb
Rails.application.routes.draw do
  
  namespace :sofa_gallery, :path => '' do
    
    resources :galleries, :only => [:show, :index]
    
    namespace :admin, :path => SofaGallery.config.admin_route_prefix do
      resources :galleries do
        resources :photos do
          put :reorder, :on => :collection
          get :crop,    :on => :member
        end
      end
    end unless SofaGallery.config.admin_route_prefix.blank?
  end
  
end

app/models/sofa/photo.rb
class Sofa::Photo < ActiveRecord::Base
  
  set_table_name :sofa_photos
  
  upload_options = (SofaGallery.config.upload_options || {}).merge(
    :styles => lambda { |image|
      g = image.instance.gallery
      @force_ratio = ">"
      f_settings = "#{g.full_width}x#{g.full_height}#{g.force_ratio?? '#' : '>'}"
      t_settings = "#{g.thumb_width}x#{g.thumb_height}#{@force_ratio}"
      {
        :full         => { :geometry => f_settings, :processors => [:cropper] },
        :thumb        => { :geometry => t_settings, :processors => [:cropper] },
        :admin_full   => '800x600>',
        :admin_thumb  => '40x30#'
      }
    }
  )
  has_attached_file :image, upload_options 
  
  before_post_process :compare_image_dimensions
  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  
  # -- Relationships --------------------------------------------------------
  belongs_to :gallery
  
  # -- Callbacks ------------------------------------------------------------
  before_create :assign_position
  after_update :reprocess_image, :if => :cropping?
  
  # -- Validations ----------------------------------------------------------
  validates :gallery_id,
    :presence => true
  validates_attachment_presence :image,
    :message      => 'There was no file uploaded!'
  validates_attachment_content_type :image,
    :content_type => %w(image/jpeg image/pjpeg image/gif image/png image/x-png),
    :message      => 'Please only upload .jpg, .jpeg, .gif or .png files.'
  validates_attachment_size :image,
    :less_than    => 5.megabytes
      
  # -- Scopes ---------------------------------------------------------------
  default_scope order(:position)
  
  # -- Instance Methods -----------------------------------------------------
  def compare_image_dimensions
    geo = Paperclip::Geometry.from_file(image.queued_for_write[:original])
    logger.info("**************************************ORIGINAL WIDTH:" << geo.width.to_s)
    g = image.instance.gallery
    logger.info("**************************************FULL WIDTH:" << g.full_width.to_s)
    if geo.width <= g.thumb_width
      @force_ratio = ""
    end
  end
  
  def image_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(image.path(style))
  end
  
  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end
  
private
  
  def assign_position
    max = self.gallery.photos.maximum(:position)
    self.position = max ? max + 1 : 0
  end
  
  def reprocess_image
    image.reprocess!
  end
  
end

app/models/sofa_gallery/photo.rb
class SofaGallery::Photo < ActiveRecord::Base
  
  set_table_name :sofa_gallery_photos
  
  upload_options = (SofaGallery.config.upload_options || {}).merge(
    :styles => lambda { |image|
      g = image.instance.gallery
      f_settings = "#{g.full_width}x#{g.full_height}#{g.force_ratio_full?? '#' : '>'}"
      t_settings = "#{g.thumb_width}x#{g.thumb_height}#{g.force_ratio_thumb?? '#' : '>'}"
      {
        :full         => { :geometry => f_settings, :processors => [:full_cropper] },
        :thumb        => { :geometry => t_settings, :processors => [:thumb_cropper] },
        :admin_full   => '800x600>',
        :admin_thumb  => '40x30#'
      }
    }
  )
  has_attached_file :image, upload_options 
  
  attr_accessor :thumb_crop_x, :thumb_crop_y, :thumb_crop_w, :thumb_crop_h, 
                :full_crop_x, :full_crop_y, :full_crop_w, :full_crop_h
  
  # -- Relationships --------------------------------------------------------
  belongs_to :gallery
  
  # -- Callbacks ------------------------------------------------------------
  before_create :assign_position
  after_update :reprocess_image, :if => :cropping?
  
  # -- Validations ----------------------------------------------------------
  validates :gallery_id,
    :presence => true
  validates :slug,
    :presence   => true,
    :uniqueness => true,
    :format     => { :with =>  /^\w[a-z0-9_-]*$/i }
  validates_attachment_presence :image,
    :message      => 'There was no file uploaded!'
  validates_attachment_content_type :image,
    :content_type => %w(image/jpeg image/pjpeg image/gif image/png image/x-png),
    :message      => 'Please only upload .jpg, .jpeg, .gif or .png files.'
  validates_attachment_size :image,
    :less_than    => 5.megabytes
  
  # -- Instance Methods -----------------------------------------------------
  def image_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(image.path(style))
  end
  
  def force_aspect?
    self.gallery.force_ratio_full? || self.gallery.force_ratio_thumb?    
  end
  
  def cropping?
    cropping_thumb? || cropping_full?
  end
  
  def cropping_thumb?
    !thumb_crop_x.blank? && !thumb_crop_y.blank? && !thumb_crop_w.blank? && !thumb_crop_h.blank?
  end
  
  def cropping_full?
    !full_crop_x.blank? && !full_crop_y.blank? && !full_crop_w.blank? && !full_crop_h.blank?
  end
  
private
  
  def assign_position
    max = self.gallery.photos.maximum(:position)
    self.position = max ? max + 1 : 0
  end
  
  def reprocess_image
    image.reprocess!
  end
  
end

app/controllers/cms_admin/photos_controller.rb
class CmsAdmin::PhotosController < CmsAdmin::BaseController
  
  before_filter :load_gallery
  before_filter :load_photo,  :only => [:edit, :update, :destroy]
  before_filter :build_photo, :only   => [:new, :create]

  def index
    @photos = @gallery.photos.all
  end

  def new
    render
  end
  
  def create
    p 'AAAAA', @photo
    
    @photo = @gallery.photos.create!(:image => params[:file])
    
    render :partial => 'file', :object => @photo
  rescue ActiveRecord::RecordInvalid
    render :nothing => true, :status => :bad_request
  end


  def edit
    render 
  end

  def update
    @photo.update_attributes!(params[:photo])
    flash[:notice] = 'Photo was successfully updated.'
    redirect_to cms_admin_gallery_photos_path(@gallery)
  rescue ActiveRecord::RecordInvalid
    render :action => :edit
  end
  
  def destroy
    @photo.destroy
  end
  
  def reorder
    (params[:photo] || []).each_with_index do |id, index|
      if (photo = Photo.find_by_id(id))
        photo.update_attribute(:position, index)
      end
    end
    render :nothing => true
  end

protected
  
  def load_gallery
    @gallery = Gallery.find(params[:gallery_id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Gallery not found', :status => 404
  end

  def load_photo
    @photo = @gallery.photos.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Photo not found', :status => 404
  end
  
  def build_photo
    @photo = @gallery.photos.new(params[:photo])
  end
  
end

app/controllers/gallery_admin/photos_controller.rb
class GalleryAdmin::PhotosController < GalleryAdmin::BaseController
  
  before_filter :load_gallery
  before_filter :load_photo,  :only => [:edit, :update, :destroy, :crop]
  before_filter :build_photo, :only => [:new, :create]

  def index
    @photos = @gallery.photos
  end

  def new
    render
  end
  
  def create
    @photo.save!
    flash[:notice] = 'Photo created'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash[:error] = 'Failed to create Photo'
    render :action => :new
  end
  
  def edit
    render
  end
  
  def update
    @photo.update_attributes!(params[:photo])
    flash[:notice] = 'Photo updated'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to updated Photo'
    render :action => :edit
  end
  
  def destroy
    @photo.destroy
    flash[:notice] = 'Photo deleted'
    redirect_to :action => :index
  end
  
  def reorder
    (params[:sofa_photo] || []).each_with_index do |id, index|
      if (photo = Sofa::Photo.find_by_id(id))
        photo.update_attribute(:position, index)
      end
    end
    render :nothing => true
  end
  
  def crop
    render
  end
  
protected
  
  def load_gallery
    @gallery = Sofa::Gallery.find(params[:gallery_id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Gallery not found'
    redirect_to gallery_admin_galleries_path
  end
  
  def load_photo
    @photo = @gallery.photos.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Photo not found'
    redirect_to :action => :index
  end
  
  def build_photo
    @photo = Sofa::Photo.new({:gallery => @gallery}.merge(params[:photo] || {}))
  end
  
end

app/controllers/sofa_gallery/admin/photos_controller.rb
class SofaGallery::Admin::PhotosController < SofaGallery::Admin::BaseController
  
  before_filter :load_gallery
  before_filter :load_photo,  :only => [:edit, :update, :destroy, :crop]
  before_filter :build_photo, :only => [:new, :create]

  def index
    @photos = @gallery.photos
  end

  def new
    render
  end
  
  def create
    file_array  = params[:sofa_gallery_photo][:image] || [nil]
    
    file_array.each_with_index do |file, i|
      file_params = params[:sofa_gallery_photo].merge(:image => file)
      
      title = (file_params[:title].blank? && file_params[:image] ? 
        file_params[:image].original_filename : 
        file_params[:title]
      )
      title = title + " #{i + 1}" if file_params[:title] == title && file_array.size > 1
      
      slug = (file_params[:slug].blank? && file_params[:image] ? 
        file_params[:image].original_filename.parameterize : 
        file_params[:slug]
      )
      slug = (slug + "-#{i + 1}") if file_params[:slug] == slug && file_array.size > 1
      
      @photo = SofaGallery::Photo.new({:gallery => @gallery}.merge(file_params.merge(:title => title, :slug => slug) || {}))
      @photo.save!
    end
    
    flash[:notice] = 'Photo created'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash[:error] = 'Failed to create Photo'
    render :action => :new
  end
  
  def edit
    render
  end
  
  def update
    @photo.update_attributes!(params[:sofa_gallery_photo])
    flash[:notice] = 'Photo updated'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to updated Photo'
    render :action => :edit
  end
  
  def destroy
    @photo.destroy
    flash[:notice] = 'Photo deleted'
    redirect_to :action => :index
  end
  
  def reorder
    (params[:sofa_gallery_photo] || []).each_with_index do |id, index|
      if (photo = SofaGallery::Photo.find_by_id(id))
        photo.update_attribute(:position, index)
      end
    end
    render :nothing => true
  end
  
  def crop
    render
  end
  
protected
  
  def load_gallery
    @gallery = SofaGallery::Gallery.find(params[:gallery_id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Gallery not found'
    redirect_to sofa_gallery_admin_galleries_path
  end
  
  def load_photo
    @photo = @gallery.photos.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Photo not found'
    redirect_to :action => :index
  end
  
  def build_photo
    @photo = SofaGallery::Photo.new({:gallery => @gallery}.merge(params[:sofa_gallery_photo] || {}))
  end
  
end

app/views/sofa_gallery/admin/photos/_form.html.erb
<%= form.text_field :title, :id => (@photo.new_record?? 'slugify' : nil) %>
<%= form.text_field :slug, :id => 'slug' %>
<% if @photo.image? && @photo.id.present? %>
  <%= form.simple_field 'Current Image' do %>
    <%= image_tag(@photo.image.url(:thumb)) %>
    <br/>
    <%= link_to 'Crop Image', crop_sofa_gallery_admin_gallery_photo_path(@gallery, @photo) if @photo.force_aspect? %>
  <% end %>
<% end %>
<%= form.file_field :image, :multiple => true %>
<%= form.text_area :description %>
<%= form.simple_field nil, nil, :class => 'submit_element' do %>
  <%= link_to "Cancel", sofa_gallery_admin_gallery_photos_path(@photo.gallery), :id => 'cancel_btn' %>
  <span>or</span>
  <%= form.submit "Save", :disable_builder => true%>
<% end %>

app/views/sofa_gallery/admin/photos/crop.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'sofa_gallery/jquery.jcrop.css' %>
  <%= javascript_include_tag 'sofa_gallery/jquery.jcrop.js' %>
  <script type="text/javascript" charset="utf-8">
    $(function(){
      $('#crop_full').Jcrop({
        onChange: update_full_crop,
        onSelect: update_full_crop,
        aspectRatio: <%= @photo.gallery.force_ratio_full?? (@photo.gallery.full_width.to_f / @photo.gallery.full_height) : 'null' %>
      });
      
      $('#crop_thumb').Jcrop({
        onChange: update_thumb_crop,
        onSelect: update_thumb_crop,
        aspectRatio: <%= @photo.gallery.force_ratio_thumb?? (@photo.gallery.thumb_width.to_f / @photo.gallery.thumb_height) : 'null' %>
      });
    });
    
    
    function update_full_crop(coords) {
      var ratio = <%= @photo.image_geometry(:original).width %> / <%= @photo.image_geometry(:admin_full).width %>;
      $('#full_crop_x').val(coords.x * ratio);
      $('#full_crop_y').val(coords.y * ratio);
      $('#full_crop_w').val(coords.w * ratio);
      $('#full_crop_h').val(coords.h * ratio);
    }
    
    function update_thumb_crop(coords) {
      var ratio = <%= @photo.image_geometry(:original).width %> / <%= @photo.image_geometry(:admin_full).width %>;
      $('#thumb_crop_x').val(coords.x * ratio);
      $('#thumb_crop_y').val(coords.y * ratio);
      $('#thumb_crop_w').val(coords.w * ratio);
      $('#thumb_crop_h').val(coords.h * ratio);
    }
  </script>
<% end %>

<h1> Crop Photo </h1>

<%= sofa_gallery_form_for @photo, :as => :photo, :url => { :action => :update } do |form| %>

  <% if @photo.gallery.force_ratio_full? %>
    <%= form.simple_field 'Full Size' do %>
      <%= image_tag @photo.image.url(:admin_full), :id => 'crop_full' %>
    <% end %>
  <% end %>
  <br />
  <% if @photo.gallery.force_ratio_thumb? %>
    <%= form.simple_field 'Thumbnail' do %>
      <%= image_tag @photo.image.url(:admin_full), :id => 'crop_thumb' %>
    <% end %>
  <% end %>


  <% [:full_crop_x, :full_crop_y, :full_crop_w, :full_crop_h].each do |attr| %>
    <%= form.hidden_field attr, :id => attr %>
  <% end %>
  
  <% [:thumb_crop_x, :thumb_crop_y, :thumb_crop_w, :thumb_crop_h].each do |attr| %>
    <%= form.hidden_field attr, :id => attr %>
  <% end %>
  
  <%= form.submit 'Crop' %>
<% end %>

app/views/sofa_gallery/admin/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= sofa_gallery_form_for @photo, :url => { :action => :update }, :html => { :multipart => true } do |form| %>
  <%= render :partial => form %>
<% end %>

app/views/sofa_gallery/admin/photos/index.html.erb
<%= link_to 'Add new photo', new_sofa_gallery_admin_gallery_photo_path(@gallery), :class => 'big button' %>

<h1>Photos in <%=@gallery.title%></h1>

<table class='formatted'>
  <tbody class='sortable'>
    <% @photos.each do |photo| %>
      <tr id='<%= dom_id(photo) %>'>
        <td>
          <%= image_tag(photo.image.url(:admin_thumb), :class => 'thumb dragger') %>
        </td>
        <td class='main'>
          <div class='title'><%= photo.title %></div>
          <div class='sublabel'><%= photo.slug %></div>
        </td>
        <td class='action_links'>
          <%= link_to 'Crop', crop_sofa_gallery_admin_gallery_photo_path(@gallery, photo) if photo.force_aspect? %>
          <%= link_to 'Edit', edit_sofa_gallery_admin_gallery_photo_path(@gallery, photo) %>
          <%= link_to 'Delete', sofa_gallery_admin_gallery_photo_path(@gallery, photo), :method => :delete, :confirm => 'Are you sure?' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sofa_gallery/admin/photos/new.html.erb
<h1>New Photo</h1>

<%= sofa_gallery_form_for @photo, :url => {:action => :create}, :html => {:multipart => true} do |form|%>
  <%= render :partial => form %>
<% end -%>