config/routes.rb
Rails.application.routes.draw do
  
  namespace :sofa_gallery, :path => '' do
    
    resources :galleries, :only => [:show, :index]
    
    namespace :admin, :path => SofaGallery.config.admin_route_prefix do
      resources :galleries do
        resources :photos do
          put :reorder, :on => :collection
          get :crop,    :on => :member
        end
      end
    end unless SofaGallery.config.admin_route_prefix.blank?
  end
  
end

app/models/sofa/gallery.rb
class Sofa::Gallery < ActiveRecord::Base
  
  set_table_name :sofa_galleries
  
  # -- Relationships --------------------------------------------------------
  has_many :photos, :dependent => :destroy
  
  # -- Validations ----------------------------------------------------------
  validates :title,
    :presence => true
    
  validates :slug,
    :presence   => true,
    :uniqueness => true,
    :format     => { :with =>  /^\w[a-z0-9_-]*$/i }
    
end

app/models/sofa_gallery/gallery.rb
class SofaGallery::Gallery < ActiveRecord::Base
  
  cms_is_categorized if defined?(ComfortableMexicanSofa)

  set_table_name :sofa_gallery_galleries
  
  # -- Relationships --------------------------------------------------------
  has_many :photos, :dependent => :destroy
  
  # -- Validations ----------------------------------------------------------
  validates :title,
    :presence => true
    
  validates :slug,
    :presence   => true,
    :uniqueness => true,
    :format     => { :with =>  /^\w[a-z0-9_-]*$/i }
    
end

app/controllers/cms_admin/galleries_controller.rb
class CmsAdmin::GalleriesController < CmsAdmin::BaseController
  
  before_filter :load_gallery,  :except => [:index, :new, :create]
  before_filter :build_gallery, :only   => [:new, :create]
  
  def index
    @galleries = Gallery.all
  end
  
  def new
    render
  end
  
  def create
    @gallery.save!
    flash[:notice] = 'Gallery was successfully created.'
    redirect_to :action => :index   
  rescue ActiveRecord::RecordInvalid
    render :action => :new
  end
  
  def show
    render
  end
  
  def edit
    render
  end
  
  def update
    @gallery.update_attributes!(params[:gallery])
    flash[:notice] = 'Gallery was successfully updated.'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    render :action => :edit
  end
  
  def destroy
    @gallery.destroy
    flash[:notice] = 'Gallery was successfully deleted.'
    redirect_to :action => :index
  end
  
protected
  
  def load_gallery
    @gallery = Gallery.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Gallery not found', :status => 404
  end
  
  def build_gallery
    @gallery = Gallery.new(params[:gallery])
  end
  
end

app/controllers/gallery_admin/galleries_controller.rb
class GalleryAdmin::GalleriesController < GalleryAdmin::BaseController
  
  before_filter :load_gallery,  :except => [:index, :new, :create]
  before_filter :build_gallery, :only   => [:new, :create]
  
  def index
    @galleries = Sofa::Gallery.all
  end
  
  def new
    render
  end
  
  def create
    @gallery.save!
    flash[:notice] = 'Gallery created'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to create Gallery'
    render :action => :new
  end
  
  def show
    render
  end
  
  def edit
    render
  end
  
  def update
    @gallery.update_attributes!(params[:gallery])
    flash[:notice] = 'Gallery updated'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to update Gallery'
    render :action => :edit
  end
  
  def destroy
    @gallery.destroy
    flash[:notice] = 'Gallery deleted'
    redirect_to :action => :index
  end
  
protected
  
  def load_gallery
    @gallery = Sofa::Gallery.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Gallery not found'
    redirect_to :action => :index
  end
  
  def build_gallery
    @gallery = Sofa::Gallery.new(params[:gallery])
  end
  
end

app/controllers/sofa_gallery/admin/galleries_controller.rb
class SofaGallery::Admin::GalleriesController < SofaGallery::Admin::BaseController
  
  before_filter :load_gallery,  :except => [:index, :new, :create]
  before_filter :build_gallery, :only   => [:new, :create]
  
  def index
    if params[:category].present?
      @galleries = SofaGallery::Gallery.for_category(params[:category]).all
    else
      @galleries = SofaGallery::Gallery.all
    end
  end
  
  def new
    render
  end
  
  def create
    @gallery.save!
    flash[:notice] = 'Gallery created'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to create Gallery'
    render :action => :new
  end
  
  def show
    render
  end
  
  def edit
    render
  end
  
  def update
    @gallery.update_attributes!(params[:gallery])
    flash[:notice] = 'Gallery updated'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to update Gallery'
    render :action => :edit
  end
  
  def destroy
    @gallery.destroy
    flash[:notice] = 'Gallery deleted'
    redirect_to :action => :index
  end
  
protected
  
  def load_gallery
    @gallery = SofaGallery::Gallery.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Gallery not found'
    redirect_to :action => :index
  end
  
  def build_gallery
    @gallery = SofaGallery::Gallery.new(params[:gallery])
  end
  
end

app/controllers/sofa_gallery/galleries_controller.rb
class SofaGallery::GalleriesController < ApplicationController
  
  def index
    @galleries = SofaGallery::Gallery.all
  rescue ActiveRecord::RecordNotFound
    render :text => 'Gallery not found', :status => 404
  end
  
  def show
    @gallery = SofaGallery::Gallery.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Gallery not found', :status => 404
  end
  
end

app/views/sofa_gallery/admin/galleries/_form.html.erb
<%= form.text_field :title, :id => (@gallery.new_record?? 'slugify' : nil)%>
<%= form.text_field :slug, :id => 'slug' %>
<%= form.text_area  :description%>

<%= form.text_field :full_width %>
<%= form.text_field :full_height %>
<%= form.check_box :force_ratio_full, :label => "Force Ratio" %>
<%= form.text_field :thumb_width %>
<%= form.text_field :thumb_height %>
<%= form.check_box :force_ratio_thumb, :label => "Force Ratio" %>

<%= render :partial => 'cms_admin/categories/form', :object => form if defined?(ComfortableMexicanSofa) %>

<%= form.simple_field nil, nil, :class => 'submit_element' do %>
  <%= link_to "Cancel", sofa_gallery_admin_galleries_path, :id => 'cancel_btn' %>
  <span>or</span>
  <%= form.submit "Save", :disable_builder => true%>
<% end %>

app/views/sofa_gallery/admin/galleries/edit.html.erb
<h1>Editing <%= @gallery.title %></h1>

<%= sofa_gallery_form_for @gallery, :as => :gallery, :url => { :action => :update } do |form|%>
  <%= render :partial => form %>
<% end %>

app/views/sofa_gallery/admin/galleries/index.html.erb
<%= link_to 'Add new gallery', new_sofa_gallery_admin_gallery_path, :class => 'big button' %>

<h1>Galleries</h1>

<%= render :partial => 'cms_admin/categories/index', :object => 'SofaGallery::Gallery' if defined?(ComfortableMexicanSofa) %>

<br />

<table class='formatted'>
  <tr>
    <th>
      Preview
    </th>
    <th>
      Name
    </th>
    <th>
      URL
    </th>
    <th>
      Embed Code
    </th>
    <th>
      Actions
    </th>
  </tr>
  <% @galleries.each do |gallery| %>
    <tr>
      <td class='preview'>
        <% gallery.photos.limit(1).each do |photo| %>
          <%= image_tag(photo.image.url(:admin_thumb)) %>
        <% end %>
      </td>
      <td class='main'>
        <%= link_to gallery.title, sofa_gallery_admin_gallery_photos_path(gallery) %>
      </td>
      <td>
        <%= link_to sofa_gallery_gallery_path(gallery), sofa_gallery_gallery_path(gallery), :target => '_blank' %>
      </td>
      <td class='embed'>
        {{ cms:helper:render_gallery:<%= gallery.slug  %> }}
      </td>
      <td class='action_links'>
        <%= link_to 'Show Photos', sofa_gallery_admin_gallery_photos_path(gallery) %>
        <%= link_to 'Edit', edit_sofa_gallery_admin_gallery_path(gallery) %>
        <%= link_to 'Delete', sofa_gallery_admin_gallery_path(gallery), :method => :delete, :confirm => 'Are you sure?' %>
      </td>
    </tr>
  <% end %>
</table>

app/views/sofa_gallery/admin/galleries/new.html.erb
<h1>New Gallery</h1>

<%= sofa_gallery_form_for @gallery, :as => :gallery, :url => { :action => :create } do |form| %>
  <%= render :partial => form %>
<% end %>